import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { FaMusic } from 'react-icons/fa';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='bg-white flex items-center justify-center h-screen'>
        <div>
        <Image alt='banner image' className='rounded-t-lg' src='/images/illustration-hero.svg' width={400} height={400}/>
          <h4 className='font-bold'>Order Summary</h4>
          <p>You can now listen to millions of songs, audiobooks, and podcasts on any device anywhere you like!</p>

          <div className='bg-blue-100 grid grid-rows-2 grid-flow-col w-1/2'>
            <div className='row-span-2'>
              <span className='rounded-full bg-indigo-300'>
                <FaMusic className='text-slate-900'/>
              </span>
            </div>
            <div className='col-span-2'>Annual Plan</div>
            <div className='col-span-2'>$59.99/year</div>
          </div>
        </div>
          
        </div>
      </main>
    </>
  )
}
